### PR TITLE
Added some niceties

### PR DESCRIPTION
**Pull request by JacksonWrath**
I forked this for some quality-of-life improvements I wanted to make. Here they are in case you'd like them as well!

### CODE REVIEW

**Comment by marsqing** [comment]
Looks good, a little question, why not do "xdo.mouse_up(1).unwrap()" in GESTURE_SWIPE_END?

**Comment by JacksonWrath** [comment]
Had to make some more significant changes to send XDo commands on a timer. I'm new to Rust, so if there's a better way to do this, I'm open to suggestions!

**Comment by marsqing** [comment]
Is it ok to do nothing at [line 89](https://github.com/JacksonWrath/libinput-three-finger-drag/blob/18400ef582cc934c60136184c68435eec15458c0/src/main.rs#L89) so we can save cpu on non-gesture events?

**Comment by JacksonWrath** [comment]
Ha, okay so, in looking into the CPU usage, I found a small bug in the intended behavior of ignoring accidental GESTURE_HOLD events. Pushed a fix for that.

We can't do nothing at that line without reverting the ability to reposition fingers while dragging. That line is there because of the [mouse_up_delay](https://github.com/JacksonWrath/libinput-three-finger-drag/blob/18400ef582cc934c60136184c68435eec15458c0/src/main.rs#L71). If you move the pointer before the delay finishes, it needs to immediately send a `mouse_up` event so you don't drag futher than you intended.

That said, I tested with this line removed and CPU was the same (in htop at least, within 0.1%). All it's doing on most events is [a few conditional statements](https://github.com/JacksonWrath/libinput-three-finger-drag/blob/18400ef582cc934c60136184c68435eec15458c0/src/xdo_handler.rs#L61-L67). It only actually sends the `mouse_up` to libxdo if it's currently in the middle of a drag; otherwise it just returns immediately back to the main loop. I believe the bulk of CPU is spent on the [string find](https://github.com/JacksonWrath/libinput-three-finger-drag/blob/18400ef582cc934c60136184c68435eec15458c0/src/main.rs#L38) and `libinput debug-events`.

**Comment by JacksonWrath** [comment]
I'm actually already considering if this could be done with the actual [libinput bindings](https://github.com/Smithay/input.rs) instead of debug-events to see what effect that has on CPU, but I'll play with that on another branch and let you know if it has a positive result.

**Comment by marsqing** [comment]
Nice work! Also the libinput binding solution would be much better than the current implementation. Look forward to that!

**Pull request merged**
